import type { AgentConversation, HerdrRuntimeState } from '@/domain/herdr';

export const FAKE_HERDR_RUNTIME: HerdrRuntimeState = {
  connectionState: 'connected',
  herdrVersion: '0.8.2',
  herdrProtocol: 20,
  herdrSession: 'default',
  workspaces: [
    { id: 'w1', name: 'herdr-mobile', status: 'working' },
    { id: 'w2', name: 'backend', status: 'blocked' },
    { id: 'w3', name: 'research', status: 'done' },
    { id: 'w4', name: 'prototype', status: 'idle' },
  ],
  agents: [
    {
      id: 'fake-copilot',
      provider: 'copilot',
      providerSessionId: 'copilot-session',
      herdrSessionId: 'default',
      workspaceId: 'w1',
      workspaceName: 'herdr-mobile',
      paneId: 'p1',
      cwd: '~/projects/herdr-mobile',
      status: 'working',
      title: 'GitHub Copilot',
      focused: true,
      capabilities: {
        structuredConversation: true,
        streamingConversation: true,
        structuredQuestions: true,
        toolActivity: true,
        todos: true,
        fallback: true,
      },
    },
    {
      id: 'fake-claude',
      provider: 'claude',
      providerSessionId: 'claude-session',
      herdrSessionId: 'default',
      workspaceId: 'w2',
      workspaceName: 'backend',
      paneId: 'p2',
      cwd: '~/projects/backend',
      status: 'blocked',
      title: 'Claude Code',
      focused: false,
      capabilities: {
        structuredConversation: true,
        streamingConversation: false,
        structuredQuestions: true,
        toolActivity: true,
        todos: false,
        fallback: true,
      },
    },
    {
      id: 'fake-codex',
      provider: 'codex',
      providerSessionId: 'codex-session',
      herdrSessionId: 'default',
      workspaceId: 'w3',
      workspaceName: 'research',
      paneId: 'p3',
      cwd: '~/research/benchmark',
      status: 'done',
      title: 'Codex',
      focused: false,
      capabilities: {
        structuredConversation: true,
        streamingConversation: false,
        structuredQuestions: false,
        toolActivity: false,
        todos: false,
        fallback: true,
      },
    },
    {
      id: 'fake-opencode',
      provider: 'opencode',
      providerSessionId: 'opencode-session',
      herdrSessionId: 'default',
      workspaceId: 'w4',
      workspaceName: 'prototype',
      paneId: 'p4',
      cwd: '~/projects/prototype',
      status: 'idle',
      title: 'OpenCode',
      focused: false,
      capabilities: {
        structuredConversation: false,
        streamingConversation: false,
        structuredQuestions: false,
        toolActivity: false,
        todos: false,
        fallback: true,
      },
    },
  ],
};

export const FAKE_COPILOT_CONVERSATION: AgentConversation = {
  agentId: 'fake-copilot',
  provider: 'copilot',
  semantic: true,
  items: [
    { id: 'u1', kind: 'user_message', text: 'Fix the reconnect issue.' },
    {
      id: 'a1',
      kind: 'assistant_message',
      markdown: 'I’ll inspect the connection lifecycle.',
    },
    {
      id: 't1',
      kind: 'tool_activity',
      title: 'Reading',
      detail: 'SshConnectionManager.kt',
      state: 'completed',
    },
    {
      id: 'q1',
      kind: 'human_request',
      request: {
        id: 'question-1',
        kind: 'choice',
        question: 'Which implementation should I use?',
        options: [
          { id: 'flow', label: 'StateFlow' },
          { id: 'callbacks', label: 'Callbacks' },
        ],
        allowCustomAnswer: true,
        multiSelect: false,
      },
    },
    {
      id: 'permission-1',
      kind: 'human_request',
      request: {
        id: 'permission-1',
        kind: 'permission',
        question: 'Allow this command once?',
        options: [
          { id: 'deny', label: 'Deny' },
          { id: 'allow-once', label: 'Allow once' },
        ],
        allowCustomAnswer: false,
        multiSelect: false,
      },
    },
  ],
};

export const FAKE_RECONNECTING_RUNTIME: HerdrRuntimeState = {
  ...FAKE_HERDR_RUNTIME,
  connectionState: 'reconnecting',
};
